version: "3"

volumes:
  ${Volume_Aplication}:
  ${Volume_Apps}:
  ${Volume_Data}:
  ${Volume_DB}:
  
networks:
  ${NETWORK_FRONTEND}:
    name: ${NETWORK_FRONTEND}
  ${NETWORK_BACKEND}:
    name: ${NETWORK_BACKEND}

services:
  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      -  ${Volume_Aplication}:/var/www/html
      -  ${Volume_Data}:/var/www/html/data
      -  ${Volume_Apps}:/var/www/html/custom_apps
      
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PORT_HTTP}:80
      - ${PORT_HTTPS}:443
    
    networks:
      - ${NETWORK_FRONTEND}
      - ${NETWORK_BACKEND}

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${Volume_DB}:/var/lib/mysql
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ${NETWORK_BACKEND}
