version: "3"

volumes:
  code-server:
  
networks:
  frontend:
    name: frontend
    
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PASSWORD: ${PASSWORD} #optional
      SUDO_PASSWORD: ${SUDO_PASSWORD} #optional
      PROXY_DOMAIN: ${PROXY_DOMAIN} #optional
    volumes:
      - code-server:/config
    ports:
      - 8443:8443
    restart: unless-stopped