version: "3"

volumes:
  code-server:
  
networks:
  frontend:
    name: frontend
    
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    volumes:
      - code-server:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PASSWORD: ${PASSWORD} #optional
      SUDO_PASSWORD: ${SUDO_PASSWORD} #optional
      PROXY_DOMAIN: ${PROXY_DOMAIN} #optional
    ports:
      - 8443:8443
    networks:
      - frontend
