version: '3'

volumes:
  vol_music:
    name: ${VOLUME_NAME_MUSIC}
    external: true
  vol_playlists:
    name: ${VOLUME_NAME_PLAYLISTS}
    external: true
  vol_data:
    name: ${VOLUME_NAME_DATA}
    external: true
  
networks:
  net:
    name: ${NETWORK}
    external: true

services:
  subsonic-app:
    image: stuckj/subsonic:latest
    container_name: ${APP_HOSTNAME}
    hostname: ${APP_HOSTNAME}
    restart: unless-stopped
    volumes:
      - vol_music:${SUBSONIC_DEFAULT_MUSIC_FOLDER}
      - vol_playlists:${SUBSONIC_DEFAULT_PLAYLIST_FOLDER}
      - vol_data:${SUBSONIC_HOME}
    environment:
      - LANG=${LANG}
      - LANGUAGE=${LANGUAGE}
      - SUBSONIC_HOME=${SUBSONIC_HOME}
      - SUBSONIC_HOST=${SUBSONIC_HOST}
      - SUBSONIC_PORT=4040
      - SUBSONIC_HTTPS_PORT=${SUBSONIC_HTTPS_PORT}
      - SUBSONIC_CONTEXT_PATH=${SUBSONIC_CONTEXT_PATH}
      - SUBSONIC_MAX_MEMORY=${SUBSONIC_MAX_MEMORY}
      - SUBSONIC_DEFAULT_MUSIC_FOLDER=${SUBSONIC_DEFAULT_MUSIC_FOLDER}
      - SUBSONIC_DEFAULT_PODCAST_FOLDER=${SUBSONIC_DEFAULT_PODCAST_FOLDER}
      - SUBSONIC_DEFAULT_PLAYLIST_FOLDER=${SUBSONIC_DEFAULT_PLAYLIST_FOLDER}
      - SUBSONIC_UID=${SUBSONIC_UID}
      - SUBSONIC_GID=${SUBSONIC_GID}
    expose:
      - 5000
    networks:
      - net

