version: "3"
volumes:
  calibre-books:
  calibre-config:
  
networks:
  frontend:
    name: frontend
    
services:
  calibre-web:
    restart: unless-stopped
    image: linuxserver/calibre-web
    container_name: calibre-web
    volumes:
      - calibre-config:/config
      - calibre-books:/books
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOCKER_MODS: linuxserver/calibre-web:calibre
    ports:
      - ${PORT}:8083
    networks:
      - frontend
