version: "3"

volumes:
  vol_data:
    name: ${VOLUME_NAME}
    external: true
  
networks:
  net:
    name: ${NETWORK_TYPE}
    external: true
    
services:
  code-server:
    container_name: ${HOSTNAME}
    hostname: ${HOSTNAME}
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    volumes:
      - vol_data:/config
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PASSWORD: ${PASSWORD}
      SUDO_PASSWORD: ${SUDO_PASSWORD}
    expose:
      - 8443
    networks:
      - net
